#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
openvpn --config /etc/openvpn/ovpn_tcp/$1.tcp.ovpn --auth-user-pass /etc/openvpn/pass.txt --script-security 2 --up /etc/openvpn/update-resolv-conf.bash --down /etc/openvpn/update-resolv-conf.bash
sysctl -w net.ipv6.conf.all.disable_ipv6=0
sysctl -w net.ipv6.conf.default.disable_ipv6=0
sysctl --system
