#!/bin/bash

for i in /proc/asound/card*/pcm*/sub*/status; do
    if grep -q "state: RUNNING" $i
    then
        exit;
    fi
done
echo 'running xautolock: shutdownSound' | systemd-cat
systemctl suspend-then-hibernate &
