#!/bin/bash
usbkbd=`xinput -list | grep -c "CM Storm Quickfire TKL 6keys  "`
usbkbdN=`xinput -list | grep -c "CM Storm Quickfire TKL Nkeys  "`
if [[ "$usbkbd" -gt 0 ]]
then
    usbkbd_ids=`xinput -list | grep "CM Storm Quickfire TKL 6keys   " | awk -F'=' '{print $2}' | cut -c 1-2`
    usbkbd_layout="tr(f)"
fi
if [[ "$usbkbdN" -gt 0 ]]
then
    usbkbd_ids=`xinput -list | grep "CM Storm Quickfire TKL Nkeys Keyboard" | awk -F'=' '{print $2}' | cut -c 1-2`
    usbkbd_layout="tr(f)"
fi

for ID in $usbkbd_ids
do
  setxkbmap -device "${ID}" -option altwin:swap_lalt_lwin
  setxkbmap -device "${ID}" -option caps:swapescape
  setxkbmap -device "${ID}" -option ctrl:swap_rwin_rctl 
done

exit 0
